#https://github.com/awaragi/prometheus-mssql-exporter
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql-exporter-prometheus-redis-exporter
  labels:
    app.kubernetes.io/name: mssql-exporter
    app.kubernetes.io/part-of: mssql-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mssql-exporter-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app.kubernetes.io/name: mssql-exporter
    app.kubernetes.io/part-of: mssql-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mssql-exporter
      app.kubernetes.io/part-of: mssql-exporter
  endpoints:
  - port: metric
    interval: 15s  
---  
apiVersion: v1
kind: Service
metadata:
  name: mssql-exporter
  labels:
    app.kubernetes.io/name: mssql-exporter
    app.kubernetes.io/part-of: mssql-exporter
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: metric
  selector:
    app.kubernetes.io/name: mssql-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-exporter
  labels:
    app.kubernetes.io/name: mssql-exporter
    app.kubernetes.io/part-of: mssql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mssql-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mssql-exporter
    spec:
      securityContext:
        {}
      containers:
        - name: mssql-exporter
          securityContext:
            null
          image: "awaragi/prometheus-mssql-exporter"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          env:
            - name: "USERNAME"
              value: sa
            - name: "PASSWORD"
              value: "MysecretPassword"
            - name: "SERVER"
              value: "192.168.1.1"  
            - name: "DEBUG"
              value: "app,metrics,db,queries"  
            - name: "PORT"
              value: "1433"  
          resources:
            {}
