name: Build and Publish
on:
  release:
    types: [published]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print tag number
        run: echo Publishing to tag ${{ github.event.release.tag_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (release tag)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: awaragi/prometheus-mssql-exporter:${{ github.event.release.tag_name }}
      - name: Build and push (latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: awaragi/prometheus-mssql-exporter:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: awaragi/prometheus-mssql-exporter
